export const twoWordsRegexp = /[0-9a-zA-Z]{3,}\W[0-9a-zA-Z]{3,}/;
export const dateRegexp = /^\s*(3[01]|[12][0-9]|0?[1-9])\.(1[012]|0?[1-9])\.((?:19|20)\d{2})\s*$/g;
export const passRegexp = /^\S+$/;

export const prevInventaTitle = 'Предыдущие инвентаризации';
export const bottlesDBTitle = 'База данных позиций';
export const addManuallyMessage = 'Сейчас нужно внести данные вручную, а мы постараемся добавить эти позиции как можно скорее';
export const createInventaHeader = 'Внесите данные';
export const emptyRegistration = { email: '', password: '', secreteKey: '',  name: '' };
export const emptyLogin = { email: '', password: '' };
export const emptyManualBottle = { title: '', volume: '', rest: '' };
export const emptyBottle = {
  title: '',
  volume: '',
  bottleCapWeight: '',
  madeIn: '',
  fullWeight: '',
  bottleModel: '',
  bottleWeight: '',
  label: '',
  barcode: '',
  alcoType: '',
}
export const testBottle = {
  title: 'JackDaniels',
  volume: 0.7,
  bottleCapWeight: 0.03,
  madeIn: 'USA',
  fullWeight: 1,
  bottleModel: 'Regular',
  bottleWeight: 0.2,
  label: 'WWW.address.com',
  barcode: 123456789098,
  alcoType: 'whiskey',
}

export const bottles = [
  {
    title: 'Jack Daniels',
    volume: 0.7,
    bottleCapWeight: 0.05,
    fullWeight: .9,
    bottleWeight: .2,
    barcode: 123456789009876,
    alcoType: 'Виски',
    label: 'wertyj',
    madeIn: 'USA',
    bottleModel: 'regular',
    _id: '1234567654sfv'
  },
  {
    title: 'Absolute',
    volume: 1,
    bottleCapWeight: 0.05,
    fullWeight: 1,
    bottleWeight: .2,
    barcode: 123456789009876,
    alcoType: 'Водка',
    label: 'wertyj',
    madeIn: 'USA',
    bottleModel: 'regular',
    _id: 'skfjnrfelnsv'
  }
];

export const inventas = [
  {
    nameInCharge: 'Dave',
    barName: 'Door Bar',
    date: '12.05.2018',
    _id: '123f45',
  },
  {
    nameInCharge: 'Ann',
    barName: 'Gym Bar',
    date: '12.10.2019',
    _id: '1s2345',
  },

  {
    nameInCharge: 'Bob',
    barName: 'Fountain Bar',
    date: '09.08.2025',
    _id: '123f455',
  },
  {
    nameInCharge: 'Cat',
    barName: 'Eagle Bar',
    date: '22.12.2021',
    _id: '12123f45',
  },
  {
    nameInCharge: 'Viniamin',
    barName: 'Codlin Bar',
    date: '29.05.2021',
    _id: '123454321',
  },
];

export const inventa = {
  nameInCharge: 'Viniamin',
  barName: 'Codlin Bar',
  date: '29.05.2021',
  _id: '123454321',
  creator: 'Viniamin',
  inventaData: [
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 3.2,
      title: 'Orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12332421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 3.2,
      title: 'Orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12332421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 3.2,
      title: 'Orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12332421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 3.2,
      title: 'Orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12332421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 3.2,
      title: 'Orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12332421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 3.2,
      title: 'Orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12332421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 3.2,
      title: 'Orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12332421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 3.2,
      title: 'Orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12332421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 2.2,
      title: 'orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '12343421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 1.2,
      title: 'orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '1235421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'orabella de Italiano',
      alcoType: 'Белое вино',
      _id: '1234ygf21',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Jack',
      alcoType: 'Виски',
      _id: '1233642421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Jack',
      alcoType: 'Виски',
      _id: '123324gb21',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Jack',
      alcoType: 'Виски',
      _id: '1233sfg2421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Jack',
      alcoType: 'Виски',
      _id: '1233bgf2421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Cariba',
      alcoType: 'Ром',
      _id: '1233ert642421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Cariba',
      alcoType: 'Ром',
      _id: '1233vr24gb21',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Cariba',
      alcoType: 'Ром',
      _id: '1233sfgs2421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Cariba',
      alcoType: 'Ром',
      _id: '1233bgfff2421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Absolute',
      alcoType: 'Водка',
      _id: '1233ert6d42s421',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Absolute',
      alcoType: 'Водка',
      _id: '1233vr24ggbs21',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Absolute',
      alcoType: 'Водка',
      _id: '1233sfgs243s21',
      isUnknown: false,
    },
    {
      fullBottle: 6,
      openedBottle: 1,
      totalVolume: 4.2,
      title: 'Absolute',
      alcoType: 'Водка',
      _id: '1233bgfff2sl421',
      isUnknown: false,
    },
  ]
}
